server:
  port: 9060

spring:
  application:
    name: potm-sba
  security: # 配置登录用户名和密码
    user:
      name: root
      password: 123456
    boot:
      admin:
        discovery:
          ignored-services: potm-sba
  cloud:
    nacos:
      serverAddr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
